In [12]:
import pandas as pd

In [13]:
data = pd.read_csv("~/Downloads/basicNeeds.csv")
data

,Legislative District,TANF and State Family Assistance,TANF Use Rate,Basic Food Program,Basic Food Use Rate,"Aged, Blind, Disabled (ABD) Assistance",ABD Use Rate,Working Connections Child Care (WCCC),WCCC Use Rate,Housing and Essential Needs (HEN) Referral,HEN Use Rate,Any Economic Services Administration (ESA) Service,Any ESA Use Rate,Population
0,1,703,0,9352,0,438,0,959,0,106,0,16422,0,159308
1,2,2412,0,24774,0,487,0,2628,0,235,0,39620,0,152987
2,3,5635,0,50383,0,1867,0,5069,0,773,0,66312,0,140083
3,4,2931,0,28483,0,758,0,3217,0,251,0,41653,0,149047
4,5,689,0,7607,0,277,0,773,0,84,0,14624,0,153230
5,6,2643,0,24672,0,590,0,2778,0,207,0,35327,0,146948
6,7,2629,0,30817,0,611,0,2007,0,265,0,42091,0,143045
7,8,2997,0,32158,0,695,0,3542,0,205,0,45767,0,152477
8,9,2133,0,23997,0,379,0,2770,0,116,0,35273,0,153937
9,10,1212,0,16453,0,523,0,1347,0,144,0,25570,0,146584
10,11,2380,0,24648,0,877,0,3099,0,202,0,34885,0,148723
11,12,1946,0,25528,0,497,0,3547,0,212,0,37272,0,145509
12,13,2744,0,31069,0,600,0,3773,0,241,0,43237,0,147668
13,14,3882,0,36253,0,656,0,3974,0,313,0,50315,0,142950
14,15,4513,0,45557,0,578,0,6745,0,233,0,61558,0,143623
15,16,2929,0,33838,0,645,0,3894,0,170,0,46913,0,144321
16,17,2367,0,25927,0,475,0,2690,0,181,0,39407,0,152203
17,18,1048,0,14393,0,246,0,1180,0,127,0,23991,0,154432
18,19,4696,0,40996,0,1129,0,3292,0,680,0,56339,0,138807
19,20,3309,0,31162,0,729,0,2650,0,398,0,45323,0,143752
20,21,1710,0,19078,0,704,0,2170,0,193,0,28915,0,155896
21,22,2493,0,26241,0,692,0,2823,0,371,0,38733,0,152822
22,23,1324,0,15541,0,322,0,1370,0,128,0,24749,0,143507
23,24,2305,0,28882,0,701,0,1932,0,354,0,39819,0,141958
24,25,2476,0,26083,0,577,0,2926,0,194,0,40695,0,148228
25,26,1703,0,18921,0,447,0,1432,0,172,0,29105,0,148775
26,27,3488,0,34251,0,978,0,3049,0,414,0,48447,0,143902
27,28,2349,0,22839,0,534,0,2614,0,181,0,36081,0,144577
28,29,5703,0,48763,0,1092,0,5534,0,348,0,68467,0,147083
29,30,3461,0,32328,0,902,0,4342,0,291,0,45679,0,147835
30,31,1876,0,18725,0,414,0,1924,0,182,0,31427,0,152397
31,32,1427,0,17641,0,848,0,1463,0,228,0,25401,0,144049
32,33,3799,0,33282,0,1174,0,5033,0,405,0,45839,0,145736
33,34,1489,0,19579,0,560,0,2528,0,234,0,27358,0,151238
34,35,2442,0,25561,0,576,0,1921,0,338,0,37065,0,144000
35,36,489,0,8435,0,644,0,359,0,200,0,11822,0,167352
36,37,2684,0,34242,0,1946,0,3425,0,646,0,44102,0,157001
37,38,2928,0,31108,0,1271,0,3360,0,486,0,45573,0,146779
38,39,1723,0,22025,0,704,0,2118,0,188,0,34136,0,146656
39,40,1623,0,20815,0,562,0,2153,0,213,0,29096,0,144538
40,41,411,0,5330,0,359,0,467,0,52,0,8999,0,150904
41,42,2061,0,26485,0,687,0,2077,0,291,0,36017,0,149643
42,43,408,0,10282,0,832,0,366,0,281,0,13071,0,173641
43,44,1055,0,12663,0,507,0,1443,0,143,0,22191,0,153400
44,45,361,0,5421,0,253,0,527,0,79,0,9855,0,149465
45,46,993,0,10801,0,497,0,986,0,179,0,15212,0,149079
46,47,3036,0,26916,0,920,0,3627,0,276,0,38071,0,149334
47,48,631,0,8048,0,470,0,733,0,101,0,12357,0,151660
48,49,3236,0,35801,0,730,0,3419,0,448,0,51394,0,149210

In [15]:
with open('basicNeeds.json', 'w') as f:
    f.write(data.to_json(orient='records'))